CREATE TABLE IF NOT EXISTS GOAL (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOAL_NAME           VARCHAR(128) NOT NULL,
    DESCRIPTION         TEXT,
    GOAL_CATEGORY       ENUM('HEALTH', 'EDUCATION', 'FINANCE'),
    START_DATE          TIMESTAMP NOT NULL,
    END_DATE            TIMESTAMP
);