CREATE TABLE IF NOT EXISTS HABIT (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    HABIT_NAME      VARCHAR(255) NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    FREQUENCY       INT,
    FREQUENCY_UNIT  ENUM('DAILY', 'WEEKLY', 'MONTHLY')
);

