CREATE TABLE IF NOT EXISTS HABIT (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    HABIT_NAME      VARCHAR(255) NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    FREQUENCY       INT,
    FREQUENCY_UNIT  ENUM('DAILY', 'WEEKLY', 'MONTHLY'),
    PROGRESS        TEXT,
    goal_id         BIGINT,
    statistics_id   BIGINT,
    FOREIGN KEY (goal_id) REFERENCES GOAL(id),
    FOREIGN KEY (`statistics_id`) REFERENCES STATISTICS(`id`)
);

