CREATE TABLE IF NOT EXISTS STATISTICS(
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOAL_NAME       VARCHAR(255),
    goal_id         BIGINT,
    STATUS          ENUM('IN_PROGRESS', 'PLANNED', 'COMPLETED', 'CANCELLED', 'FAILED'),
    FOREIGN KEY (goal_id) REFERENCES GOAL(id)
);