CREATE TABLE IF NOT EXISTS STATISTICS(
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    habit_id        BIGINT,
    goal_id         BIGINT,
    COMPLETION_DATE DATE,
    STATUS          ENUM('IN_PROGRESS','COMPLETED','CANCELLED','FAILED'),
    FOREIGN KEY (habit_id) REFERENCES HABIT(id),
    FOREIGN KEY (goal_id) REFERENCES GOAL(id)
);