CREATE TABLE IF NOT EXISTS ACTIVITY (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    TIMESTAMP       DATETIME NOT NULL,
    habit_id        BIGINT NOT NULL,
    FOREIGN KEY (habit_id) REFERENCES HABIT(id)
    );

