CREATE TABLE IF NOT EXISTS ACTIVITY (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACTIVITY_NAME   VARCHAR(255) NOT NULL,
    TIME_OF_ACTIVITY TIME,
    DATE_OF_ACTIVITY DATE NOT NULL,
    habit_id        BIGINT NOT NULL,
    FOREIGN KEY (habit_id) REFERENCES HABIT(id)
    );

